### ISSUE TITLE
Something is off with Safari

### ISSUE THREAD

**Issue by mgatelabs** [markuslerner/THREE.Interactive#12]
I'm trying to figure out what is going on with my app and safari.  I was able to trace it down to THREE.Interactive as the part which causes the crash.  The crash only tells me "SyntaxError: Left hand side of operator '=' must be a reference." and something about promiseReactionJob, but no other details, no line number.

What I tried:

- I've played with my code and removed Three.Interactive, and it starts working.
- Tried to isolate things and only reference classes like this console.log(InteractionManager); and it still fails.
- I included the main ts file from Three.Interactive and removed the dependency and it works.
- Development builds are working, only production suffers, so should be something with the optimizer

So it feels like something is off when the dependency is used, since if I natively bring in the class and use it, everything is fine.  I know THREE had a similar issue a few years ago from this page: https://github.com/angular/angular-cli/issues/21107

Repo: https://github.com/mgatelabs/GenshinSolvers
Live: https://mgatelabs.github.io/GenshinSolvers/ (This will have the internal version of Three.Interactive for now)

Also, I tried the sample apps linked to the Readme and in safari they are working, so unsure what is going on.

**Comment by markuslerner** [comment]
Hi, please try using version v.1.3.0 and let me know, if the problem still persists.

**Comment by mgatelabs** [comment]
I'll give it a try, thanks

**Comment by mgatelabs** [comment]
Tried it locally, and it seems to be working, Nice!

**Comment by markuslerner** [comment]
Cool, thank you for letting me know, @mgatelabs!
