### ISSUE TITLE
Not working with three 140

### ISSUE THREAD

**Issue by Pandan** [markuslerner/THREE.Interactive#15]
I am having problem installing the npm package.
npm ERR! Could not resolve dependency:
npm ERR! peer three@"^0.138.0" from three.interactive@1.3.1

I am using "three": "^0.140.2"

Using -force solves the problem. 
npm i --force three.interactive

**Comment by markuslerner** [comment]
Dear @Pandan, thank you for pointing this out. I set the three peerDependency to ">= 0.122.0" now and published release 1.3.2. I tested it with successfully with webpack and three@0.140.2. Please let me know, if it works for you as well now.

**Comment by Pandan** [comment]
Thanks, it worked great

**Comment by markuslerner** [comment]
Thank you @Pandan. I'm closing this issue now.
