### ISSUE TITLE
Uncaught TypeError: Error resolving specificator module « three »

### ISSUE THREAD

**Issue by swiinger** [markuslerner/THREE.Interactive#17]
Hello Mark,

Thanks for your great work
I try to integrate your module on a webserver but I get this error, I think it's because my browser can't resolve the name "three" in your code (import{Raycaster as a,Vector2 as h}from"three")
I have tried to change "three" with "https://threejs.org/build/three.min.js" where belong three.js on my server but i get an other error :
Uncaught SyntaxError: ambiguous indirect export: Raycaster

Any thoughts ?
Thanks
Chris

**Comment by swiinger** [comment]
Ok found it out : I have to replace "three" with "https://cdnjs.cloudflare.com/ajax/libs/three.js/0.144.0/three.module.js" which contains all the modules needed

**Comment by markuslerner** [comment]
@swiinger, great that you were able to fix it! Best Markus
