### ISSUE TITLE
expected 4 arguments, but got 3

### ISSUE THREAD

**Issue by ariferol01** [markuslerner/THREE.Interactive#18]
```
const interactionManager = new InteractionManager(
          renderer,
          camera,
          renderer.domElement
        );
```

**Comment by markuslerner** [comment]
Hi @ariferol01, thank you for pointing this out. I declared the 4th argument as optional in typescript. Please try [Release 1.5.1](https://github.com/markuslerner/THREE.Interactive/releases/tag/v1.5.1) and let me know, if it works for you now.
