### ISSUE TITLE
On mobile onclick not working

### ISSUE THREAD

**Issue by teunes1** [markuslerner/THREE.Interactive#19]
On android one plus 8 with chrome and many other mobile devices the clickmanager is not working. It only works after rotating the phone to landscape mode. 

The onclick handlers does work in portrait but not on the 3d object it self it feels like the click register happens on the wrong orientantion. That it using the height/wiodthto see if it clicks on the object instead of height/width.

**Comment by markuslerner** [comment]
Hi @teunes1, have you tried using the "pointerdown" instead of the "click" event? Can you send a link to the page or paste your code here?

**Comment by teunes1** [comment]
Hey @markuslerner i've the same problem with the example code:

```
import * as THREE from 'three';
import { InteractionManager } from 'three.interactive';

const container = document.createElement('div');
container.setAttribute('id', 'container');
document.body.appendChild(container);

const renderer = new THREE.WebGLRenderer();
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setSize(window.innerWidth, window.innerHeight);
container.appendChild(renderer.domElement);

const scene = new THREE.Scene();

const camera = new THREE.PerspectiveCamera(
  45,
  window.innerWidth / window.innerHeight,
  0.1,
  1000
);
camera.position.set(0.0, 0.0, 10.0);

const interactionManager = new InteractionManager(
  renderer,
  camera,
  renderer.domElement
);

const geometry = new THREE.BoxGeometry(1, 1, 1);
const material = new THREE.MeshBasicMaterial();

const cube = new THREE.Mesh(geometry, material);
cube.addEventListener('mouseover', (event) => {
  event.target.material.color.set(0xff0000);
  document.body.style.cursor = 'pointer';
});
cube.addEventListener('mouseout', (event) => {
  event.target.material.color.set(0xffffff);
  document.body.style.cursor = 'default';
});
cube.addEventListener('mousedown', (event) => {
  event.target.scale.set(1.1, 1.1, 1.1);
});
cube.addEventListener('click', (event) => {
  event.target.scale.set(1.0, 1.0, 1.0);
});
scene.add(cube);
interactionManager.add(cube);

const animate = (time) => {
  requestAnimationFrame(animate);

  interactionManager.update();

  renderer.render(scene, camera);
};

animate();
```

I use laravel framework with vite to parse the file and the result is preloading the javascript:
`<link rel="modulepreload" href="https://mydomain.nl/build/assets/app.9a6b6a82.js" /><script type="module" src="https://mydomain.nl/build/assets/app.9a6b6a82.js"></script>`
Not sure if this is relevant, but this might be the only thing that is different.

The installed package versions are:
`  "three": "^0.146.0", // 0.149 is installed(latest)
        "three.interactive": "^1.5.0// 1.5.1 is installed(latest)"`

Tried pointerdown as well.

The weird part is that for example in chrome if use the inspection tool with a mobile device it is working as expected but running it on mobile with chrome(everything up to date) it is not working.

**Comment by markuslerner** [comment]
Hi @teunes1, thank you for the code. I tested it on the latest Chrome mobile app on my iPhone Xs and it works. Unfortunately I don't have an Android phone at the moment.

I used the simple.html file as a base for testing you code and the "yarn start" script of THREE.interactive.

– Have you tried adding a "handleWindowResize" handler as in the simple.html example?

– Are you using this meta tag or a similar one in your <head>?
`<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />`

– Have you tried pasting your code into that example?

– I have also just released the new version 1.5.2 of this library, which adds a check for touchEvent.touches.length > 0, which might also solve your problem.

Please let me know, if any of this works for you.

**Comment by teunes1** [comment]
@markuslerner  the viewport was the fix
``<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />``


Many thanks!

**Comment by markuslerner** [comment]
Glad, this worked. Thank you, @teunes1 for the feedback and for closing this issue!
