### ISSUE TITLE
mouseup bug

### ISSUE THREAD

**Issue by anthonypena97** [markuslerner/THREE.Interactive#3]
On my end, v.1.1.0

mouseup triggers outside of specified object.

had to implement this workaround to work as wanted . looking for 'intersected' key value to be true.

```html
object.addEventListener('mouseup', function (event) {

            if (event.intersected) {

                   console.log('hello');

            }

        })
```

**Comment by markuslerner** [comment]
Hi Anthony, that is actually intended behaviour. If you want the mouse up to fire only on the object you can also use the "click" event.
