### ISSUE TITLE
Prevent pointermove/mousemove events on the body element

### ISSUE THREAD

**Issue by Bossieh** [markuslerner/THREE.Interactive#4]
First of all thanks for this awesome lib, really helpfull in a project I am working on.

And it seems that the InteractionManager also binds mousemove/pointermove events to the body element:

https://github.com/markuslerner/THREE.Interactive/blob/d02c1c54fa8126d97c3302eb33f7f4cd809b80d7/src/index.js#L47

In my situation I show a popup when someone clicks something in the 3D scene. But hover events are still fired when someone moves his mouse in the popup.

A simple option to prevent the event binding to the body would be great.

**Comment by Bossieh** [comment]
Also: I can add this function and open a pull request if you want?

**Comment by markuslerner** [comment]
Hi Edwin,

yes, sure that would be great! Thank you.

I know these events can be very tricky to handle depending on platform, browser and use case.

Best
Markus

**Comment by markuslerner** [comment]
Parameter dontBindEventsOnBody added in [release v1.2.1](https://github.com/markuslerner/THREE.Interactive/releases/tag/v1.2.1).
